snyk/nodejs-lockfile-parser

.travis.yml
appveyor.yml
package.json

Adjusting `package.json` for semantic release
* npm package will be called `snyk-nodejs-lockfile-parser`, and will be public
Enabling travis and appveyor configs

fix: enable semantic release, travis and appveyor CI

---

package-lock.json
package.json

Trying a new `semantic-release` version to overcome travis/gh/npmjs incompatibilities and make the release happen!

fix: upgrade semantic-release to enable releases on travis

---

bin/index.js
lib/index.ts
package.json
test/lib/fixtures/goof/dep-tree_small.json
test/lib/index.ts

- 💥 Tests written and linted [ℹ︎]() 
Introduces a recursive algorithm for creation of dependency tree from `package-lock.json` and `package.json`.
I did my best to comment the algorithm, but feel free to suggest any naming or other structural improvements.
- [SC-5885]()

Parse lockfile recursively

---

.gitignore
lib/index.ts
package-lock.json
test/lib/fixtures/dev-deps-only/expected-tree.json
test/lib/fixtures/dev-deps-only/package-lock.json
test/lib/fixtures/dev-deps-only/package.json
test/lib/fixtures/missing-deps/expected-tree.json
test/lib/fixtures/missing-deps/package-lock.json
test/lib/fixtures/missing-deps/package.json
test/lib/fixtures/missing-name/package-lock.json
test/lib/fixtures/missing-name/package.json
test/lib/fixtures/package-repeated-in-manifest/expected-tree.json
test/lib/fixtures/package-repeated-in-manifest/package-lock.json
test/lib/fixtures/package-repeated-in-manifest/package.json
test/lib/fixtures/undefined-deps/package-lock.json
test/lib/fixtures/undefined-deps/package.json
test/lib/index.ts

Added more tests for:
- devDependencies only are present
- Same dependency appears twice (once in dependencies and once more in devDependencies)
- empty dependencies and varying the `--dev` flag
Run this locally
- [SC-5985](https://snyksec.atlassian.net/browse/SC-5985)

feat: add support for different type of dependencies

---

lib/index.ts
lib/parsers/index.ts
lib/parsers/package-lock-parser.ts
lib/parsers/yarn-lock-parse.ts
tsconfig.json

Adds strict compilation in order to be compliant with Typescript consumers with strict compilation enabled.
- [SC-5891](https://snyksec.atlassian.net/browse/SC-5891)

fix: enable strict compilation and address findings

---

lib/index.ts
test/lib/fixtures/dev-deps-only/expected-tree-empty.json
test/lib/package-lock.ts

Even though `dependencies` is a required field for npm, `npm init` doesn't seem to generate this property and users can easily not add the `dependencies` to the file. Return empty tree if this happens and do not error.
- [SC-6322](https://snyksec.atlassian.net/browse/SC-6322)

fix: Allow package.json to have missing dependency property

---

lib/index.ts

In order to catch/error properly, it will be handy to re-recreate exactly same error from outside world.
Allows catching/stubbing real errors from outside world (handy for testing different reactions by consumers of lockfile parser.

feat: export error classes

---

lib/parsers/package-lock-parser.ts
lib/set-immediate-promise.ts
package.json
test/lib/fixtures/cyclic-dep-self-reference/cyclic-dep-self-reference-2/package.json
test/lib/fixtures/cyclic-dep-self-reference/package-lock.json
test/lib/fixtures/cyclic-dep-self-reference/package.json
test/lib/package-lock.ts

🚧 **DO NOT MERGE** 🚧
Big `package-lock.json` parsing was slow. This PR introduces better parsing algorithm, which speeds up parsing a lot. 
Proper testing is still needed to be sure that functionality is the same. Tests are passing*, but they can't cover everything. However, it's pretty hard to verify what's right for the output with ~million lines.
\* I am aware about one failing, it's a topic for the discussion about the meaning of `depType` property.
*Before:*
```
$ time parse-nodejs-lockfile > /dev/null
parse-nodejs-lockfile > /dev/null  30.25s user 1.24s system 123% cpu 25.522 total
```
*After:*
```
$ time node ../lockfile-parser/bin > /dev/null
node ../lockfile-parser/bin > /dev/null  0.39s …
```

perf: faster package-lock tree creation

---

lib/index.ts
test/lib/package-lock.ts
test/lib/yarn.ts

When package name is missing use manifest filename instead
https://snyksec.atlassian.net/browse/SC-6758### Screenshots

feat: lockfile parser must always return `depTree.name`

---

lib/parsers/index.ts
lib/parsers/package-lock-parser.ts
lib/parsers/yarn-lock-parse.ts
test/lib/fixtures/dev-deps-only/expected-tree-empty.json
test/lib/fixtures/dev-deps-only/expected-tree.json
test/lib/fixtures/external-tarball/expected-tree.json
test/lib/fixtures/file-as-version/expected-tree.json
test/lib/fixtures/git-ssh-url-deps/expected-tree.json
test/lib/fixtures/goof/dep-tree-no-dev-deps-yarn.json
test/lib/fixtures/goof/dep-tree-no-dev-deps.json
test/lib/fixtures/goof/dep-tree-with-dev-deps-yarn.json
test/lib/fixtures/goof/dep-tree-with-dev-deps.json
test/lib/fixtures/missing-deps/expected-tree.json
test/lib/fixtures/out-of-sync-tree/expected-tree.json
test/lib/fixtures/out-of-sync/expected-tree.json
test/lib/fixtures/package-repeated-in-manifest/expected-tree.json

We want to know how many dependencies totally in the tree. It's useful for debug purposes when, for example, we want to measure why so much time we spend on parsing.

feat: add tree size in the output

---

package.json

fixes these vulns:
* https://dev.snyk.io/vuln/SNYK-JS-LODASH-73638
* https://dev.snyk.io/vuln/SNYK-JS-LODASH-73639

fix: bump vulnerable lodash 4.17.10 to ^4.17.11

---

lib/index.ts
lib/parsers/index.ts
test/lib/fixtures/yarn-workspace/package.json
test/lib/yarn.ts

Identify if a `package.json` is a yarn workspace, we can start using this to log/treat/process these projects differenly

feat: Allow us to identify yarn workspaces in package.json

---

lib/parsers/index.ts
lib/parsers/package-lock-parser.ts
lib/parsers/yarn-lock-parse.ts
test/lib/fixtures/goof/dep-tree-no-dev-deps-yarn.json
test/lib/fixtures/goof/dep-tree-no-dev-deps.json
test/lib/fixtures/goof/dep-tree-original.json
test/lib/fixtures/goof/dep-tree-with-dev-deps-yarn.json
test/lib/fixtures/goof/dep-tree-with-dev-deps.json
test/lib/fixtures/out-of-sync/expected-tree.json
test/lib/fixtures/package-repeated-in-manifest/expected-tree.json

Start collecting the node version as targetRuntime to be displayed in registry & used for FIX later on to make sure we execute on a similar enviroment.
Further down the line also needed to show node vulns & filter vulns that affect only certain version of node.
*Not used by anything yet, will need to raise a PR in Registry to display it + CLI to start sending it*
- [BST-559](https://snyksec.atlassian.net/browse/BST-559)

feat: Collect node version as targetRuntime

---

lib/parsers/yarn-lock-parse.ts
package.json

Some projects with dense dependencies will see 1 min shaved off
`snyk test --dev`
```Tested 1897 dependencies for known issues, found 122 issues, 21409 vulnerable paths.```
*before*
```
real	3m38.727s
user	1m15.105s
sys	0m7.165s
```
*after* with promise.all() 
```
real	2m32.861s
user	1m12.167s
sys	0m5.526s
```
*after* with pMap 😱 
```
real	0m52.625s
user	0m45.793s
sys	0m2.508s
```
- [zendesk](https://snyk.zendesk.com/agent/tickets/2993)

feat: replace for loop with Promise.all for ~1 min improvement in some cases

---

config.default.json
lib/config.ts
lib/parsers/package-lock-parser.ts
lib/parsers/yarn-lock-parse.ts
package.json
test/lib/package-lock-depTree.test.ts
test/lib/yarn.test.ts

config treeSizeLimit for yarn & npm
This will be improved in another pr with `configurable treeSizeLimit` tests for yarn & npm
Edit --
Side pr no longer necessary because the side pr upgrade are already applied on master so we could proceed with this

feat: config tree size limit for yarn and npm.

---

lib/index.ts
lib/parsers/index.ts
lib/parsers/package-lock-parser.ts
lib/parsers/yarn-lock-parse-base.ts
package.json

The upgraded `event-loop-spinner` can better share state with other libraries, hopefully leading to less yielding.
Also found some incomplete lodash reduction lying around, may as well go in!

perf: event-loop-spinner with sharing

---

lib/parsers/index.ts
test/lib/fixtures/yarn-workspace-alternate-config/package.json
test/lib/yarn-workflows.test.ts

resolves https://github.com/snyk/snyk/issues/1251
This PR addresses https://github.com/snyk/snyk/issues/1251, adding support for the alternate Yarn Workspaces configuration in `package.json` at `workspaces.packages`
```
{
"name": "my-workspace",
"private": true,
"workspaces": {
"packages": [ "packages/*" ]
}
}
```

feat: add support for yarn workspaces pattern in workspaces.packages

---

lib/index.ts
test/lib/yarn.test.ts

With the detection of yarn version from the contents of the lockfile, we can support the --yarn-workspaces flag from CLI when it's on yarn v2

feat: detect yarn version from lockfile contents

---

lib/parsers/package-lock-parser.ts
package.json

Updating dep-graph to prevent including our lodash fork.

fix: update dep-graph to use upstream lodash

---

lib/parsers/package-lock-parser.ts
package.json

`uuid` has changed the import style, and picked up five other major version changes apparently.

feat: upgrade uuid (new import style)

---

package.json

Updates to the new snyk-config version that should get shipped with the CLI first.
Requirement for https://github.com/snyk/snyk/pull/1524
Follow up to the https://github.com/snyk/config/pull/43

fix: use snyk-config version v4.0.0-rc.2

---

lib/parsers/lock-parser-base.ts
test/lib/yarn.test.ts

Shows the previous (pre https://github.com/snyk/nodejs-lockfile-parser/pull/93) OutOfSync error

fix: return to previous OutOfSync error

---

.gitignore
package.json

Update tap version in order to remove critical transitive vulns

chore: upgrade tap to remove vulns

---

lib/errors/out-of-sync-error.ts

Getting an out of sync error when using yarn2 now produces accurate messaging instead of `undefined` being present

fix: correct messaging in out of sync errors if using yarn2

---

lib/parsers/index.ts
lib/parsers/lock-parser-base.ts

Instead of passing an entire lockfile to a function that only uses it
to decide if we need to grab peer deps, do this calculation upfront
and optionally allow grabbing peer deps. This also allows for future support
of --peer

fix: pass includePeerDeps instead of a whole lockfile

---

lib/parsers/index.ts
lib/parsers/lock-parser-base.ts
test/fixtures/yarn2/scoped-resolutions/applicable-resolutions-with-scoped-pkg/expected-top-level-deps.json
test/fixtures/yarn2/scoped-resolutions/applicable-resolutions-with-scoped-pkg/package.json
test/fixtures/yarn2/scoped-resolutions/applicable-resolutions/expected-top-level-deps.json
test/fixtures/yarn2/scoped-resolutions/applicable-resolutions/package.json
test/fixtures/yarn2/scoped-resolutions/inapplicable-resolutions-with-scoped-pkg/expected-top-level-deps.json
test/fixtures/yarn2/scoped-resolutions/inapplicable-resolutions-with-scoped-pkg/package.json
test/fixtures/yarn2/scoped-resolutions/inapplicable-resolutions/expected-top-level-deps.json
test/fixtures/yarn2/scoped-resolutions/inapplicable-resolutions/package.json
test/fixtures/yarn2/simple-resolutions/expected-top-level-deps.json
test/fixtures/yarn2/simple-resolutions/package.json
test/jest/get-top-level-deps.test.ts

This makes a small fix to apply resolutions when finding top level deps. Currently scoped just to yarn2 for first rollout.

fix: applies resolutions when finding top level deps if yarn 2

---

.circleci/config.yml

This freezes the semantic release version used on the pipeline as the latest release - v18 - requires node v14+.

fix: freeze semantic release on pipeline to avoid breaking change in v18

---

lib/parsers/index.ts
test/fixtures/optional-peer-deps-npm7/direct-optional-installed/expected-tree.json
test/fixtures/optional-peer-deps-npm7/direct-optional-installed/package-lock.json
test/fixtures/optional-peer-deps-npm7/direct-optional-installed/package.json
test/fixtures/optional-peer-deps-npm7/direct-optional-not-installed/expected-tree.json
test/fixtures/optional-peer-deps-npm7/direct-optional-not-installed/package-lock.json
test/fixtures/optional-peer-deps-npm7/direct-optional-not-installed/package.json
test/fixtures/optional-peer-deps-npm7/transitive-optional-installed/expected-tree.json
test/fixtures/optional-peer-deps-npm7/transitive-optional-installed/package-lock.json
test/fixtures/optional-peer-deps-npm7/transitive-optional-installed/package.json
test/fixtures/optional-peer-deps-npm7/transitive-optional-not-installed/expected-tree.json
test/fixtures/optional-peer-deps-npm7/transitive-optional-not-installed/package-lock.json
test/fixtures/optional-peer-deps-npm7/transitive-optional-not-installed/package.json
test/fixtures/peer-deps/npm7/package-lock.json
test/lib/package-lock-depTree.test.ts

This PR aims to correct that by excluding the optional peer dependencies from the generated top-level dependency tree.
- Currently, Snyk considers that a peer dependency should be part of the lockfile if there is such dependency and the `lockfileVersion !==2`. This does not take into account the `peerDependencyMeta` and the possibility that a peer dependency can be optional (see [npm doc](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta)).
- The proposed behaviour assumes that Snyk should 'dismiss' optional peer dependency.
- Should fix #121 
- [npm, peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta).

fix: support optional peerDependencies with npm7

---

lib/parsers/lock-parser-base.ts
test/fixtures/missing-required-deps-in-lock/expected-tree.json

Maven seems to use 'unknown' (https://support.snyk.io/hc/en-us/articles/4934749708829). It would be nice to keep the wording consistent.

chore: use 'unknown' to be consistent with other ecosystems

---

lib/cli-parsers/cli-parser-utils.ts
lib/parsers/lock-parser-base.ts
package.json

This PR removes the `npm-package-arg` package and reverts to the old method when parsing package name. The reason is, `npm-package-arg` is excellent in parsing package names in `package-lock.json`, but it couldn't parse certain complicated package names in `yarn2.lock`, e.g. `resolve@patch:resolve@^1.10.0#builtin<compat/resolve>` which is using the compat plugin.

feat: remove npa package name parser and revert to old method

---

lib/parsers/index.ts
test/fixtures/yarn-workspace-missing-packages-config/package.json
test/lib/yarn-workflows.test.ts

In our old logic, we assume that the `workspaces` section in the `package.json` file would be one of the following:
```
{
"workspaces": ["packageA/**", "packageB/**"]
}
{
workspaces: {
"packages":  ["packageA/**", "packageB/**"]
}
}
```
But there could be situations that this assumption doesn't hold, in which case our code fails because we can't iterate on a non-array object. For example, it is possible that one declares only information about `nohoist`, e.g.
```
{
"workspaces":
{
"nohoist": ["packageA/**", "packageB/**"]
}
}
```
This PR strengthens the array type check on `workspaces` and `workspaces.packages` to make sure no error would be thrown.

fix: apply array type check for workspace configs

---

package.json

Upgrade `snyk-config` to a version which doesn't support node 8 anymore; we haven't supported node 8 for years.

feat: upgrade snyk-config (no more node 8)

---

lib/dep-graph-builders/index.ts
lib/dep-graph-builders/npm-lock-v2/extract-npm-lock-v2-pkgs.ts
lib/dep-graph-builders/npm-lock-v2/index.ts
lib/dep-graph-builders/types.ts
lib/dep-graph-builders/util.ts
lib/dep-graph-builders/yarn-lock-v2/build-depgraph-simple.ts
lib/index.ts
test/jest/dep-graph-builders/fixtures/npm-lock-v2/cyclic-dep/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/cyclic-dep/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/cyclic-dep/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/empty-dev-deps/expected-dev-deps-excluded.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/empty-dev-deps/expected-dev-deps-included.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/empty-dev-deps/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/empty-dev-deps/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/goof/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/goof/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/goof/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/invalid-pkg-json/package.json_content
test/jest/dep-graph-builders/fixtures/npm-lock-v2/missing-non-top-level-deps/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/missing-non-top-level-deps/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/missing-top-level-deps/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/missing-top-level-deps/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/one-dep/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/one-dep/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/one-dep/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/only-dev-deps/expected-dev-deps-excluded.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/only-dev-deps/expected-dev-deps-included.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/only-dev-deps/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/only-dev-deps/package.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts

This is a PR to add support for `package-lock.json` parsing for both lockfile versions 2 and 3. It follows the newer convention of standalone parsing function for ditinct lockfile parsing.
Additionally , it is true we curently support npm lock version 2 lockfiles but this is due to a backwards compatability consideration made by npm. This offers a new way to parse them - the same way we would parse npm lock version 3 files.

feat: npm-lock-v2 depgraph builder implementation

---

lib/dep-graph-builders/npm-lock-v2/index.ts

Initially I was using data from the package-lock.json to get root package information but the presence of [this fixture](https://github.com/snyk/cli/blob/master/test/fixtures/npm/with-vulnerable-lodash-dep/package-lock.json) made me realise this isn't always possible. 
This uses logic that we have previously used to get root package information.

fix: make sure to use pkgJson to pick the root package name

---

lib/dep-graph-builders/npm-lock-v2/extract-npm-lock-v2-pkgs.ts
lib/dep-graph-builders/npm-lock-v2/index.ts
lib/dep-graph-builders/util.ts
test/jest/dep-graph-builders/fixtures/npm-lock-v2/deeply-nested-packages/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/deeply-nested-packages/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/deeply-nested-packages/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/goof/expected.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts

This adds support for bundled dependencies inside of npm-lock-v2 projects. Previously these would be flagged as missing in lockfile.

fix: handles npm lock v2 bundled dependencies

---

.circleci/config.yml
lib/utils.ts
test/fixtures/bare-npm/package-lock.json
test/fixtures/bare-npm/package.json
test/jest/__snapshots__/get-lockfile-version.test.ts.snap
test/jest/get-lockfile-version.test.ts

Log the full error in debug mode when we fail to grab the lockfile version
Add a test for the parsong function to show it works as expected on Node 12
Enable tests on Node 12 as CLI still supports Node 12

fix: npm version parse test & enable logging

---

lib/c-map.ts
lib/dep-graph-builders/npm-lock-v2/index.ts
lib/dep-graph-builders/yarn-lock-v1/build-depgraph-simple-pruned.ts
lib/dep-graph-builders/yarn-lock-v1/build-depgraph-simple.ts
lib/dep-graph-builders/yarn-lock-v1/build-depgraph-workspace-package-pruned.ts
lib/dep-graph-builders/yarn-lock-v1/build-depgraph-workspace-package.ts
lib/dep-graph-builders/yarn-lock-v1/simple.ts
lib/dep-graph-builders/yarn-lock-v1/workspaces.ts
lib/dep-graph-builders/yarn-lock-v2/build-depgraph-simple.ts
lib/dep-graph-builders/yarn-lock-v2/simple.ts
package.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts
test/jest/dep-graph-builders/yarn-lock-v2.test.ts

This adds the [event-loop-spinner](https://github.com/snyk/event-loop-spinner) to the dep graph builders to help prevent any event-loop-blocking by the synchronous loops within recursion currently in the newer pattern. 
This obviously changes the function apis slightly.

feat: async-ify all the depgraph builder functions

---

test/jest/dep-graph-builders/npm-lock-v2.test.ts

Not all tests were being ran, this fixes it

fix: run all tests for npm lock v2

---

lib/dep-graph-builders/npm-lock-v2/index.ts
test/jest/dep-graph-builders/fixtures/npm-lock-v2/bundled-deps/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/deeply-scoped/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/different-versions/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/different-versions/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/different-versions/package.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/goof/expected.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts

This fixes a bug discovered [in this PR](https://github.com/snyk/nodejs-lockfile-parser/pull/202/files/ca913ff58600c1894085ac11cbe8d98724b07196#diff-81f70fb04fd56113a23046eb84b767b2c22af26fb791de3e071b1ecce7170fce) and separates as to release it as it's own fix, as it provides value on it's own.

fix: correctly pick npm-lock-v2 pkg version parsing lockfile

---

lib/dep-graph-builders/npm-lock-v2/index.ts

This makes a fix for workspaces that include sub pkgs that are resolved from the node_module to their file location instead of the standard way which is the other way around.

fix: correct nested pkg resolution

---

lib/dep-graph-builders/npm-lock-v2/index.ts
test/jest/dep-graph-builders/fixtures/npm-lock-v2/npm-scoped-sub-dep/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/npm-scoped-sub-dep/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/npm-scoped-sub-dep/package.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts

Previously if this parser saw a version specifier like `npm:something@^1.0.0` this whole specifier was used as the version in the depgraph. This is a bit disingenuous as we should be able to resolve the version this actually gets resolved to using the lockfile. This behavior also causes downstream issues in the Snyk CLI.
Now these versions will attempt to be resolved to just the final version range in the specifier.

fix: resolve npm scoped versions

---

lib/dep-graph-builders/npm-lock-v2/index.ts
test/jest/dep-graph-builders/fixtures/npm-lock-v2/dist-tag-sub-dependency/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/dist-tag-sub-dependency/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/dist-tag-sub-dependency/package.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts

Previously ( `v1.52.1` ) npm projects using lockfile v2 and above that had dependencies that uses the "npm [dist-tags](https://docs.npmjs.com/adding-dist-tags-to-packages)" feature were able to be scanned by this library. 
Since then thie npm lockfile v2 parsing code has been iterated upon, fixing a number of bugs. Unfortunately one of these bugs was masking the fact we did not support `dist-tags` as it was just choosing a version that matched the name. Once semver checks were added, these `dist-tags` version started to fail to be found which caused parsing to error out. 
To fix this I have skipped just the semver part of the resolution algorithm if the version provided is not valid semver, i.e. if it is a dist-tag. The algorithm then continues to look through potential parents to find a …

fix: stop hard failures on npm dist-tags

---

lib/parsers/index.ts

If the pnpm-workspace.yaml  file is empty, all packages of all subdirectories are returned, instead of throwing an error - https://pnpm.io/pnpm-workspace_yaml

fix: pnpm workspaces should return everything if config file empty

---

lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-v6.ts

Instead of matching (..) groups, which has a redos vulnerability, split string by "(". This gets the string till the first occurence of "(".
This works just fine because a package name cannot have "(" in its name (it shows up just as a separator).

fix: avoid redos by replacing regex with string split

---

lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts
lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-v5.ts
lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-v6.ts
lib/dep-graph-builders/pnpm/types.ts

The parser for pnpm lockfiles now normalises the importers object on construction/parse. This is useful for inspecting information around packages in a workspace without multiple parsers.
If not a workspace lockfile then the importers will be empty and the `importers` field on the parser will be an empty object.
- [SC-XXXX]()

feat: normalize pnpm importers on parse

---

package.json

Fix the `Inefficient Regular Expression Complexity` security issue from [micromatch@4.0.5](https://security.snyk.io/vuln/SNYK-JS-MICROMATCH-6838728).

chore: update micromatch version

---

lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts
lib/dep-graph-builders/pnpm/utils.ts
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/alias-sub-dependency/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/alias-sub-dependency/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/alias-sub-dependency/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/deeply-scoped/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/alias-sub-dependency/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/alias-sub-dependency/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/alias-sub-dependency/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/deeply-scoped/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/alias-sub-dependency/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/alias-sub-dependency/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/alias-sub-dependency/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/deeply-scoped/expected.json
test/jest/dep-graph-builders/pnpm-lock.test.ts

https://pnpm.io/aliases
pnpm aliases were not handled correctly.
In subdependencies, their version shows up as the dependency path from the packages section in the lockfile.
A package can be installed with multiple different versions for the same package.
- [OSM-1996](https://snyksec.atlassian.net/browse/OSM-1996)
[OSM-1996]: https://snyksec.atlassian.net/browse/OSM-1996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [OSM-1996] support pnpm packages aliases

---

lib/dep-graph-builders/pnpm/build-dep-graph-pnpm.ts
lib/dep-graph-builders/pnpm/utils.ts
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/missing-non-top-level-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/missing-top-level-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/missing-non-top-level-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/missing-top-level-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/missing-non-top-level-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/missing-top-level-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/npm-lock-v2.test.ts
test/jest/dep-graph-builders/pnpm-lock.test.ts
test/jest/dep-graph-builders/yarn-lock-v1-realistic-fixtures.test.ts
test/jest/dep-graph-builders/yarn-lock-v1-workspaces.test.ts

We should throw OutOfSync early if top level deps were not found in extracted lockfile packages.
Updated tests for pnpm/npm/yarn: we shouldn't use try-catch to test a failing scenario because if if the function doesn't fail as expected the test still passes

fix: fail early for top level deps out of sync pnpm and updated tests

---

lib/dep-graph-builders/pnpm/lockfile-parser/index.ts
lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-v5.ts
lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-v9.ts
lib/dep-graph-builders/pnpm/parse-project.ts
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/empty-project/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/empty-project/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/empty-project/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/empty-project/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/empty-project/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/empty-project/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/empty-project/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/empty-project/pnpm-lock.yaml
test/jest/dep-graph-builders/pnpm-lock.test.ts

Handle no dependencies projects for pnpm:
* pnpm@7 does not create a lockfile
* pnpm@8 and pnpm@9 creates a lockfile without packages/snapshots fields
It should return a dep graph with only the root package.

fix: handle pnpm empty lockfiles

---

lib/dep-graph-builders/pnpm/build-dep-graph-pnpm.ts
lib/dep-graph-builders/pnpm/constants.ts
lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts
lib/dep-graph-builders/pnpm/parse-workspace.ts
lib/dep-graph-builders/pnpm/utils.ts
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/alias-sub-dependency/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/cyclic-dep/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/external-tarball/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/git-ssh-url-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/npm-protocol/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/workspace-undefined-versions/packages/pkgs/pkg-a/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/alias-sub-dependency/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/cyclic-dep/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/external-tarball/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/git-ssh-url-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/npm-protocol/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/workspace-undefined-versions/packages/pkgs/pkg-a/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/alias-sub-dependency/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/cyclic-dep/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/external-tarball/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/git-ssh-url-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/npm-protocol/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/packages/example-components/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-undefined-versions/packages/pkgs/pkg-a/expected.json

For undefined versions of top level packages or undefined versions in general, keep the same 'undefined' string as the version.

fix: return same format for undefined versions pnpm

---

lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts
lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-v5.ts
lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-v6.ts
lib/dep-graph-builders/pnpm/utils.ts
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/git-protocol-peer-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/git-protocol-peer-deps/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/git-protocol-peer-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/git-protocol-peer-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/git-protocol-peer-deps/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/git-protocol-peer-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/git-protocol-peer-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/git-protocol-peer-deps/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/git-protocol-peer-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/pnpm-lock.test.ts

Fix for how we handle peer dependencies in dependency paths:
For example this dependency path from the lockfile:
git@github.com+linkedin/dustjs-helpers/1469a7a0297f84fba28a5101ad5305890f47e352(dustjs-linkedin@3.0.1).
The (dustjs-linkedin@3.0.1) part represents a peer transitive dependency.
Need to make sure this is removed from the dependency path in order to correctly match the top level dependency to its correspondent entry in the lockfile packages.
Added tests for this cases for all pnpm lock versions.

fix: [OSM-2329] handle peers deps in dep path for git protocol deps

---

lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts
lib/dep-graph-builders/pnpm/types.ts
lib/dep-graph-builders/util.ts
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/duplicate-dev-peer-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/duplicate-dev-peer-deps/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/duplicate-dev-peer-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/duplicate-dev-peer-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/duplicate-dev-peer-deps/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/duplicate-dev-peer-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/duplicate-dev-peer-deps/expected.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/duplicate-dev-peer-deps/package.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/duplicate-dev-peer-deps/pnpm-lock.yaml
test/jest/dep-graph-builders/pnpm-lock.test.ts

Fixes scenario where the same dependency is declared in both devDependencies and peerDependencies/dependencies.
The way pnpm installation works for this is:
* pnpm install: installs everything, the duplicate dependency is marked as dev
* pnpm install --prod: the duplicate dependency is not installed at all (being considered a dev dependency)
The option includeDevDependencies=false should mimick the pnpm install --prod.

fix: [OSM-2481] pnpm outofsync error fix for overlap dep in peer/dev deps

---

lib/dep-graph-builders/index.ts
lib/dep-graph-builders/pnpm/index.ts
lib/dep-graph-builders/pnpm/parse-workspace-project.ts
lib/index.ts
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/workspace-cyclic-root/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/workspace-cyclic-root/shared/react/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/workspace-cyclic/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/workspace-cyclic/shared/backend/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/workspace-cyclic/shared/react/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/workspace-with-cross-ref/packages/pkgs/pkg-a/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/workspace-cyclic-root/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/workspace-cyclic-root/shared/react/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/workspace-cyclic/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/workspace-cyclic/shared/backend/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/workspace-cyclic/shared/react/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/workspace-with-cross-ref/packages/pkgs/pkg-a/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-cyclic-root/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-cyclic-root/shared/react/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-cyclic/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-cyclic/shared/backend/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-cyclic/shared/react/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-with-cross-ref/packages/pkgs/pkg-a/expected-workspace-projects-undefined.json
test/jest/dep-graph-builders/pnpm-workspace-singe-project.test.ts

Added function for parsing a single package.json within a workspace. Expected input : package.json file content, pnpm-lock.yaml file content, options, importer (the relative path to the package.json file)
Unfortunately, if there's no context/access to the other package.json files, we can't determine the versions of the referenced local projects - hence the added expected outputs in tests.

feat: pnpm - function for parsing single project from a workspace

---

.circleci/config.yml
package.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts
test/jest/dep-graph-builders/pnpm-lock.test.ts
test/jest/dep-graph-builders/yarn-lock-v1-realistic-fixtures.test.ts

Updates @yarnpkg/core to fix cross-spawn vulns. : This bumps it 2 major versions https://www.npmjs.com/package/@yarnpkg/core/v/2.4.0?activeTab=versions
Updates the typescript dev dep to `"^5.4.5"` This was required to get the build passing as older versions couldn't interpret the type definitions correctly 
Updates the minimum supported node version to 18

fix: update cross-spawn vuln by updating package

---

lib/dep-graph-builders/npm-lock-v2/index.ts
test/jest/dep-graph-builders/fixtures/npm-lock-v2/bundled-top-level-dep/expected.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/bundled-top-level-dep/package-lock.json
test/jest/dep-graph-builders/fixtures/npm-lock-v2/bundled-top-level-dep/package.json
test/jest/dep-graph-builders/npm-lock-v2.test.ts
test/jest/dep-graph-builders/npm-lock-v2/get-child-key.test.ts

- [] Reviewed by Snyk team
Correctly handles top-level bundled dependencies for npm lock v2.
When a top-level dependency is bundled, all of its sub-dependencies are bundled, so the candidate keys/paths (e.g. `node_modules/dep1/node_modules/dep2`) should skip the bundled root check. The candidate keys/paths of bundled top-level deps should be treated as non-bundled top-level deps because that's how the paths show up in the locakfile.
See added unit test.

fix: [OSM-2120] npm handle bundled top level deps

---

lib/dep-graph-builders/util.ts
lib/dep-graph-builders/yarn-lock-v1/build-depgraph-simple.ts
lib/dep-graph-builders/yarn-lock-v2/build-depgraph-simple.ts
test/jest/dep-graph-builders/aliases.test.ts
test/jest/dep-graph-builders/fixtures/yarn-lock-v2/real/git-remote-url/expected.json

Adds missing alias label to nodes for yarn v1 and yarn v2.
Miss from #281, impacting the print-deps display in CLI.

fix: add missing alias labels in yarn [SOSE-22]
