appveyor.yml
Add node 4 and 6 to Appveyor config.
=> feat: Enable node 4 and 6

README.md
=> chore: adds badge

lib/index.ts, test/lib/fixtures/cyclic-dep-simple/package-lock.json, test/lib/fixtures/cyclic-dep-simple/package.json, test/lib/fixtures/cyclic-dep/package-lock.json, test/lib/fixtures/cyclic-dep/package.json, test/lib/index.ts
Fixes situation, when cyclic dependencies are found in `package-lock.json`.
- [SC-5999](https://snyksec.atlassian.net/browse/SC-5999)
=> fix: handle cyclic dependencies

package-lock.json, package.json
=> fix: Remove un-needed path dependency

lib/parsers/index.ts, lib/parsers/package-lock-parser.ts, lib/parsers/yarn-lock-parse.ts, test/lib/fixtures/dev-deps-only/expected-tree.json, test/lib/fixtures/external-tarball/expected-tree.json, test/lib/fixtures/file-as-version/expected-tree.json, test/lib/fixtures/git-ssh-url-deps/expected-tree.json, test/lib/fixtures/goof/dep-tree-no-dev-deps-yarn.json, test/lib/fixtures/goof/dep-tree-no-dev-deps.json, test/lib/fixtures/goof/dep-tree-with-dev-deps-yarn.json, test/lib/fixtures/goof/dep-tree-with-dev-deps.json, test/lib/fixtures/out-of-sync-tree/expected-tree.json, test/lib/fixtures/out-of-sync/expected-tree.json, test/lib/fixtures/package-repeated-in-manifest/expected-tree.json, test/lib/fixtures/simple-test/expected-tree.json, test/lib/fixtures/simple-test/package-lock.json, test/lib/fixtures/simple-test/package.json, test/lib/package-lock.test.ts, test/lib/yarn.test.ts
Move property `depType` to be nested in `label` property to be used in depGraph conversion.
- https://snyksec.atlassian.net/browse/BST-753
=> Feat: move dep type to label

lib/parsers/index.ts, lib/parsers/package-lock-parser.ts, lib/parsers/yarn-lock-parse.ts, test/lib/fixtures/out-of-sync/expected-tree.json, test/lib/package-lock.test.ts, test/lib/yarn.test.ts
Adding the cyclic label to be propagated when converting from tree to graph
https://snyksec.atlassian.net/browse/BST-778
=> feat: add pruned-cyclic label to nodes

.github/PULL_REQUEST_TEMPLATE.md
_Explain why this PR exists_
- [SC-XXXX]()
=> chore: fix pr template docs link

lib/errors/index.ts, lib/errors/tree-size-limit-error.ts, lib/parsers/package-lock-parser.ts
=> feat: apply limit on tree size.

.travis.yml
We were no longer creating auto semantic-releases
=> fix: semantic-release.

lib/parsers/package-lock-parser.ts, lib/parsers/yarn-lock-parse.ts, lib/set-immediate-promise.ts, package.json
replacement of `setImmediate` with `event-loop-spinner` to solve current event-loop blocking issues
=> feat: intro of eventloopSpinner lib.

.github/CONTRIBUTING.md
minor change on contributing md
=> docs: changes on contributing md.

lib/index.ts, lib/parsers/index.ts, lib/parsers/package-lock-parser.ts, lib/parsers/yarn-lock-parse.ts, package.json, test/lib/package-lock-depTree.test.ts, test/lib/yarn.test.ts
Use our fork with `zipObjectDeep` patched
=> fix: patch lodash using @snyk/lodash

lib/parsers/package-lock-parser.ts, package.json
Use patched @snyk/graphlib to remove vulnerable lodash
https://github.com/snyk/snyk/pull/1093
=> feat: use patched @snyk/graphlib

lib/index.ts, test/lib/fixtures/package-json-without-name/package-lock.json, test/lib/fixtures/package-json-without-name/package.json, test/lib/index.test.ts, test/lib/package-lock-depTree.test.ts, test/lib/yarn.test.ts, test/utils.ts
Use filename as default name instead of the full path
=> fix: use filename as default name istead of full path

lib/parsers/yarn2-lock-parse.ts
Remove `lodash` from yarn v2 parser
=> fix: remove lodash from yarn v2 parser

lib/parsers/yarn-utils.ts, package.json
Replace with lodash flatMap package
=> fix: replace with lodash flatMap package

lib/parsers/package-lock-parser.ts, package.json
Use `@snyk/graphlib` forked package to reduce dependency on lodash.
https://snyk.slack.com/archives/C01MDU3UL59/p1612973794033300
=> Use @snyk/graphlib

lib/parsers/index.ts, test/lib/fixtures/peer-deps/expected-tree.json, test/lib/fixtures/peer-deps/package-lock.json, test/lib/fixtures/peer-deps/package.json, test/lib/package-lock-depTree.test.ts
This adds the behaviour to scan peerDependencies and optionalDependencies if present.
=> feat: peer and optional dependencies now supported

lib/parsers/index.ts, test/fixtures/optional-peer-deps-npm7/direct-optional-installed/expected-tree.json, test/fixtures/optional-peer-deps-npm7/direct-optional-installed/package-lock.json, test/fixtures/optional-peer-deps-npm7/direct-optional-installed/package.json, test/fixtures/optional-peer-deps-npm7/direct-optional-not-installed/expected-tree.json, test/fixtures/optional-peer-deps-npm7/direct-optional-not-installed/package-lock.json, test/fixtures/optional-peer-deps-npm7/direct-optional-not-installed/package.json, test/fixtures/optional-peer-deps-npm7/transitive-optional-installed/expected-tree.json, test/fixtures/optional-peer-deps-npm7/transitive-optional-installed/package-lock.json, test/fixtures/optional-peer-deps-npm7/transitive-optional-installed/package.json, test/fixtures/optional-peer-deps-npm7/transitive-optional-not-installed/expected-tree.json, test/fixtures/optional-peer-deps-npm7/transitive-optional-not-installed/package-lock.json, test/fixtures/optional-peer-deps-npm7/transitive-optional-not-installed/package.json, test/fixtures/peer-deps/npm7/package-lock.json, test/lib/package-lock-depTree.test.ts
Follow through merge from the fork here https://github.com/snyk/nodejs-lockfile-parser/pull/128
=> fix: support optional peer dependencies npm

lib/parsers/lock-parser-base.ts, package.json, test/fixtures/optional-peer-deps-npm7/direct-optional-not-installed/expected-tree.json
Remove lodash.set since it brings high vuln
=> fix: remove lodash.set since it brings high vuln

lib/errors/out-of-sync-error.ts
Add some missing error message handling for projects that are using npm 7 or above
=> feat: Improve error msg for npm 7+ projects

test/jest/dep-graph-builders/fixtures/yarn-lock-v1/one-dep/expected.json, test/jest/dep-graph-builders/fixtures/yarn-lock-v1/one-dep/package.json, test/jest/dep-graph-builders/fixtures/yarn-lock-v1/workspace-with-isolated-pkgs/package.json
Sorry about this PR, the previous PR when squash merged, I didn't change the commit message and somehow it got prefixed with `*` and then broke the semantic.
So this PR is just to trigger the release 😓
=> feat: release new yarn v1 parser

lib/index.ts
Quick reorganisation of imports. Also using a fix commit message to force a release of previous mislabelled chores.
=> fix: reorganise imports and export

lib/dep-graph-builders/npm-lock-v2/index.ts, lib/dep-graph-builders/util.ts, test/jest/dep-graph-builders/fixtures/npm-lock-v2/deeply-nested-packages/expected.json, test/jest/dep-graph-builders/npm-lock-v2.test.ts
This improves the accuracy of the dependency resolution for bundled dependencies.
=> chore: improved accuracy for bundled dependencies resolution

README.md
A little house keeping to make the readme more accurate and also to generate a release that includes the last couple of commits.
=> fix: update readme and trigger release

lib/dep-graph-builders/npm-lock-v2/index.ts, package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-a/package-lock.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-a/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-a/packages/a/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-a/packages/b/expected.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-a/packages/b/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-b/package-lock.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-b/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-b/packages/a/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-b/packages/b/expected.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-glob-b/packages/b/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces/package-lock.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces/packages/a/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces/packages/b/expected.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces/packages/b/package.json, test/jest/dep-graph-builders/npm-lock-v2.test.ts
This adds support for workspaces in npm lockfile version 2 and version 3 projects - when building depgraphs.
=> feat: npm workspaces support when building dep graphs

lib/dep-graph-builders/npm-lock-v2/index.ts, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-packages/package-lock.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-packages/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-packages/packages/a/package.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-packages/packages/b/expected.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/workspaces-packages/packages/b/package.json, test/jest/dep-graph-builders/npm-lock-v2.test.ts
Looks like the parser is not working as expected for package-locks with "workspaces" with a nested package objects, this fixes this problem.
```
❯ snyk test
workspacesDeclaration.map is not a function
❯ snyk test -d
...
snyk test <ref *1> { _: [ [Circular *1] ], debug: true } +0ms
snyk-test Analyzing npm dependencies for .../package-lock.json +0ms
snyk:run-test Error running test {
error: TypeError: workspacesDeclaration.map is not a function
at resolvedToWorkspace (/snapshot/project/dist/cli/webpack:/snyk/node_modules/snyk-nodejs-lockfile-parser/dist/dep-graph-builders/npm-lock-v2/index.js:111:1)
at getChildNode (/snapshot/project/dist/cli/webpack:/snyk/node_modules/snyk-nodejs-lockfile-parser/dist/dep-graph-builders/npm-lock-v2/index.js:117:1)
at dfsVisit …
```
=> fix: correct parser nested package in workspaces

lib/dep-graph-builders/npm-lock-v2/index.ts, test/jest/dep-graph-builders/fixtures/npm-lock-v2/override-with-dep/expected.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/override-with-dep/package-lock.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/override-with-dep/package.json, test/jest/dep-graph-builders/npm-lock-v2.test.ts
This fixes dependencies of resolutions being given the override version of their parent.
=> fix: more accurately resolves deps of overrides

lib/dep-graph-builders/npm-lock-v2/index.ts, test/jest/dep-graph-builders/fixtures/npm-lock-v2/simple-version-range-override/expected.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/simple-version-range-override/package-lock.json, test/jest/dep-graph-builders/fixtures/npm-lock-v2/simple-version-range-override/package.json, test/jest/dep-graph-builders/npm-lock-v2.test.ts, test/jest/dep-graph-builders/npm-lock-v2/match-override-key.test.ts
Please look at test fixtures to understand goal.
This allows us to work with simple overrides which have a version specifier in the name.
=> fix: allow overrides with version specs

lib/dep-graph-builders/pnpm/build-dep-graph-pnpm.ts, lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts, lib/dep-graph-builders/pnpm/types.ts, lib/dep-graph-builders/pnpm/utils.ts, test/jest/dep-graph-builders/pnpm-lock.test.ts
Fixed possible missing fields (e.g. missing dependencies in lockfile) and fixed actual retrieval of optional and dev dependencies.
=> fix: fixed possible missing fields and dev/optional deps

lib/index.ts
This just exposes some logic at the top level.
- [SC-XXXX]()
=> feat: expose getPnpmParser functionality at the top level

.circleci/config.yml
fixed main branch name in circleci config
=> fix: fixed main branch name in circleci config

lib/dep-graph-builders/pnpm/parse-project.ts, lib/dep-graph-builders/pnpm/parse-workspace.ts, lib/dep-graph-builders/types.ts, test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/peer-dependencies/expected.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/peer-dependencies/package.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v5/peer-dependencies/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/peer-dependencies/expected.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/peer-dependencies/package.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v6/peer-dependencies/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/peer-dependencies/expected.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/peer-dependencies/package.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/peer-dependencies/pnpm-lock.yaml, test/jest/dep-graph-builders/pnpm-lock.test.ts
Small fix to correctly send the received `includePeerDeps` option.
=> fix: [OSM-1924] send peerDeps option

test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/expected.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/package.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/packages/example-components/expected.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/packages/example-components/package.json, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/pnpm-lock-v9/workspace-catalogs/pnpm-workspace.yaml, test/jest/dep-graph-builders/pnpm-workspaces.test.ts
Current implementation works for pnpm 9 catalog feature.
Added test for it.
=> fix: [OSM-1923] added test for catalogs feature in pnpm 9

lib/dep-graph-builders/types.ts
Remove duplicate field includePeerDeps introduced in  https://github.com/snyk/nodejs-lockfile-parser/pull/239
- [SC-XXXX]()
=> fix: remove duplicate includePeerDeps

lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts
Added debug log for workspace projects version resolution in case in is undefined.
- [SC-XXXX]()
=> fix: debug log for undefined version

lib/dep-graph-builders/npm-lock-v2/index.ts, lib/dep-graph-builders/util.ts
Reverts snyk/nodejs-lockfile-parser#239
=> Revert "Fix/ignore optional deps if not installed"

test/jest/dep-graph-builders/pnpm-lock.test.ts, test/jest/dep-graph-builders/pnpm-workspaces.test.ts
There were 2 reverts done that did not release a new version.
https://github.com/snyk/nodejs-lockfile-parser/pull/246
https://github.com/snyk/nodejs-lockfile-parser/pull/244
=> fix: small change for new version release

lib/dep-graph-builders/pnpm/build-dep-graph-pnpm.ts, lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts, lib/dep-graph-builders/pnpm/utils.ts
A small fix to take devDependencies where it is the case, instead of dependencies for pnpm parsing.
Also added some debug logs.
=> fix: fixed dev deps ref and added more debug logs

lib/dep-graph-builders/pnpm/build-dep-graph-pnpm.ts, lib/dep-graph-builders/pnpm/lockfile-parser/lockfile-parser.ts
removed optional params from extract top level deps
=> fix: removed optional params from extract top level deps

test/jest/dep-graph-builders/aliases.test.ts, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v5/pnpm-lock-with-npm-alias-also-on-transitive/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v5/pnpm-lock-with-npm-alias-also-on-transitive/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v5/pnpm-lock-with-npm-prefixed-sub-dep-version/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v5/pnpm-lock-with-npm-prefixed-sub-dep-version/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v5/pnpm-lock/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v5/pnpm-lock/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v6/pnpm-lock-with-npm-alias-also-on-transitive/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v6/pnpm-lock-with-npm-alias-also-on-transitive/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v6/pnpm-lock-with-npm-prefixed-sub-dep-version/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v6/pnpm-lock-with-npm-prefixed-sub-dep-version/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v6/pnpm-lock/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v6/pnpm-lock/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v9/pnpm-lock-with-npm-alias-also-on-transitive/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v9/pnpm-lock-with-npm-alias-also-on-transitive/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v9/pnpm-lock-with-npm-prefixed-sub-dep-version/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v9/pnpm-lock-with-npm-prefixed-sub-dep-version/pnpm-lock.yaml, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v9/pnpm-lock/package.json, test/jest/dep-graph-builders/fixtures/aliases/pnpm/pnpm-lock-v9/pnpm-lock/pnpm-lock.yaml
Adds tests for pnpm for aliases (the same ones as npm and yarn).
=> chore: add pnpm tests for aliases
